### ISSUE TITLE
Gutter markers conflict with linter-ui-default

### ISSUE THREAD

**Issue by jmatsushita** [yacut/tester#10]
Hi there,

I'm giving the tester package a try (with tester-mocha) and when I activate it or when tests are ran, the existing linter markers (and the underline decorations) disappear.

If I deactivate the `Gutter Enabled` option, then the linting information reappears. This is the case even if tester is in the `Left`position and the linter UI is in the `Right` position.

Cheers,

Jun

**Comment by yacut** [comment]
test
