### ISSUE TITLE
Tests are cleared when closing dock

### ISSUE THREAD

**Issue by Gert-dev** [yacut/tester#11]
Hello

I just updated to Atom 1.17 and am experiencing the new results view for the first time. Great work! I'll be reporting some (minor) things I encountered in the next few minutes to help improve it, but overall I'm pleased with it.

It seems that my tests results are cleared whenever I close the dock. This happens when I follow the following steps:
1. Run project tests.
2. Project tests complete, indicators are updated to reflect the state of the tests.
3. I click any of the buttons (successful tests or faulty tests), the dock opens.
4. I close the dock again by clicking the indicator from Atom.
5. All the counters reset to 0 and my test results are gone.

This feels rather unpleasant, as I may close the dock to fix some issue to get some more vertical space, but then I have to run my tests over again if I want to see the error again.

Additionally, there seems to be a rather annoying issue related to the linter-ui-default package, where the entire dock closes when you click anywhere in the tests results. However, it seems that this package is not at fault, since the problem is fixed when I disable linter-ui-default. I'll report an issue to steelbrain about this, but I thought I'd mention it in case someone else experienced this issue.

Thanks in advance!

**Comment by yacut** [comment]
The bug fix released v1.1.1

If the issue with the linter-ui-default package is in the tester package, please create a separate issue.
