### ISSUE TITLE
Register bottom dock at startup

### ISSUE THREAD

**Issue by Gert-dev** [yacut/tester#14]
Hello

The dock currently doesn't seem to be registered until you click the status bar. This is unfortunate, as it prevents the user from simply trying to expand the bottom dock by clicking Atom's indicator after starting Atom. Would it be possible to register the dock immediately at startup (possibly hidden by default, as linter-ui-default does)?

You may also be able to restore the dock's previous state: if it was opened, reopen it on Atom startup or, if it was closed, hide it by default. Atom also seems to do this with its tree-view.

Thanks in advance

**Comment by yacut** [comment]
Hello.
Thanks for the issue.
I thought about it. But I have not been able to integrate deserialization yet. Maybe later.

**Comment by yacut** [comment]
released with 1.2.0 version
