### ISSUE TITLE
Hide status bar if project has zero tests

### ISSUE THREAD

**Issue by dcalhoun** [yacut/tester#23]
A potential enhancement would be to hide the tester status bar if the project does not contain any tests. Would you be open to this addition?

### Empty Project w/ Status Bar
![empty-project-w-status-bar](https://user-images.githubusercontent.com/438664/29647380-8481dda2-884e-11e7-95e3-293aa004bb95.png)

### Empty Project w/o Status Bar
![empty-project-wo-status-bar](https://user-images.githubusercontent.com/438664/29647381-848c8c2a-884e-11e7-8379-8c9a353e6e9c.png)

**Comment by bronson** [comment]
Not sure I agree...  It might be nice if it could be grayed out or muted.  But hiding controls can get pretty frustrating, especially for new users.

**Comment by dcalhoun** [comment]
@bronson toggling visibility is the how [steelbrain/linter-ui-default](https://github.com/steelbrain/linter-ui-default) behaves. That is why I anticipated tester to behave this way. In my mind, the package UI has little benefit if a project has zero tests.

**Comment by yacut** [comment]
@bronson I don't think than is good Idea to trigger search for tests just to show or hide the status bar pane. 
What if you open empty project and add the new test? Should the tester trigger search for tests again?

The linter-ui-default status bar is visible, if the current pane is an text editor and the linter package enabled.
Additionally, the tester can start project tests and show results without any active editor.

**Comment by dcalhoun** [comment]
Valid points. Thanks for the feedback.
