### ISSUE TITLE
Babel support

### ISSUE THREAD

**Issue by gurre** [yacut/tester#24]
Hi Roman! Great project you got going here. I've been looking for exactly what you are building.
I've encountered a problem with Babel and JSX support, well it seems like it's not supported atm. Please consider bringing it to the roadmap.

**Comment by bronson** [comment]
Hi gurre.  I don't quite understand...  What is the problem with babel and jsx?  What test runner are you using?

**Comment by yacut** [comment]
@gurre Could you please give a little more information? What test runner you use (jest or mocha)? What error you get? May be reproduce steps...

**Comment by gurre** [comment]
Never mind. I missed out the additional packages for the test runners.
