### ISSUE TITLE
phpunit provider

### ISSUE THREAD

**Issue by recca0120** [yacut/tester#4]
Hi @yacut 

this package is awesome...
I love it...

I create a phpunit provider here 
https://github.com/recca0120/tester-phpunit

but it's not finished.. I'll keep develop it.

May I publish it to atom, or transfer it to your github ???

this is my first atom package. XD

**Comment by yacut** [comment]
Great work! I added PHPUnit runner to the provider list. https://github.com/yacut/tester/commit/fa64a60b1b98b29ac0fe9b8fbe5a3f8a8ccf2bf3
