### ISSUE TITLE
Integrate with busy-signal

### ISSUE THREAD

**Issue by Gert-dev** [yacut/tester#7]
Hello

I see that you're rolling your own loading spinner when the tests are running. Just wanted to let you know you can get this for free by plugging into [steelbrain's busy-signal](https://github.com/steelbrain/busy-signal) package.

This way, all packages using this one get a consistent UI. It also has neat things such as automatic history collection.

Thanks in advance

**Comment by yacut** [comment]
Hello. 
Thanks for the issue. I know about this package, but I'm still not sure whether it's a good idea to integrate a test tool into a lint tool ui. I think this will confuse the user and it would be better to make own ui.
It's already in [roadmap](https://github.com/yacut/tester#roadmap)

**Comment by yacut** [comment]
The own UI is available since 1.0.0 release.
