### ISSUE TITLE
Ability to jump to next failure

### ISSUE THREAD

**Issue by Gert-dev** [yacut/tester#8]
Hello

It would be neat if you could click a button to jump to the next test failure.

Intuitively, I wanted to click the buttons in the status bar to jump to the next error, which opened the output console instead. However, I understand others may expect the output console to open.

Thanks in advance

**Comment by yacut** [comment]
Hi. Thanks for the issue. Already in [roadmap](https://github.com/yacut/tester#roadmap)

**Comment by yacut** [comment]
The feature is available since 1.0.0 release.
