### ISSUE TITLE
Run all available tests

### ISSUE THREAD

**Issue by Gert-dev** [yacut/tester#9]
Hello

First of all, great to see that you're developing this package and exposing a service. The gutter markers are very neat and this reduces the work other package authors have to do to get testing software to integrate with Atom. We also get a consistent interface for different testing providers.

The one core feature I'm currently missing in this package is a way to run all tests in the entire project. That would allow me and others to ditch having to manually fire up a console or run a custom command to get the tests to run.

EDIT: Just noticed you already have this on the roadmap, great!

Thanks for your efforts!

**Comment by yacut** [comment]
Hi. Thanks for the issue. Already in [roadmap](https://github.com/yacut/tester#roadmap)

**Comment by yacut** [comment]
The feature is available since 1.0.0 release.
